# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: lotto.sql
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from src.db import models


CREATE_PURCHASE = """-- name: create_purchase \\:one
INSERT INTO lotto_purchases (user_id, user_name, week_key)
VALUES (:p1, :p2, :p3)
RETURNING id, user_id, user_name, week_key, purchased_at
"""


FIND_PURCHASE_BY_USER_AND_WEEK = """-- name: find_purchase_by_user_and_week \\:one
SELECT id, user_id, user_name, week_key, purchased_at
FROM lotto_purchases
WHERE user_id = :p1 AND week_key = :p2
LIMIT 1
"""


FIND_PURCHASE_BY_WEEK_KEY = """-- name: find_purchase_by_week_key \\:one
SELECT id, user_id, user_name, week_key, purchased_at
FROM lotto_purchases
WHERE week_key = :p1
LIMIT 1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_purchase(self, *, user_id: str, user_name: str, week_key: str) -> Optional[models.LottoPurchase]:
        row = self._conn.execute(sqlalchemy.text(CREATE_PURCHASE), {"p1": user_id, "p2": user_name, "p3": week_key}).first()
        if row is None:
            return None
        return models.LottoPurchase(
            id=row[0],
            user_id=row[1],
            user_name=row[2],
            week_key=row[3],
            purchased_at=row[4],
        )

    def find_purchase_by_user_and_week(self, *, user_id: str, week_key: str) -> Optional[models.LottoPurchase]:
        row = self._conn.execute(sqlalchemy.text(FIND_PURCHASE_BY_USER_AND_WEEK), {"p1": user_id, "p2": week_key}).first()
        if row is None:
            return None
        return models.LottoPurchase(
            id=row[0],
            user_id=row[1],
            user_name=row[2],
            week_key=row[3],
            purchased_at=row[4],
        )

    def find_purchase_by_week_key(self, *, week_key: str) -> Optional[models.LottoPurchase]:
        row = self._conn.execute(sqlalchemy.text(FIND_PURCHASE_BY_WEEK_KEY), {"p1": week_key}).first()
        if row is None:
            return None
        return models.LottoPurchase(
            id=row[0],
            user_id=row[1],
            user_name=row[2],
            week_key=row[3],
            purchased_at=row[4],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_purchase(self, *, user_id: str, user_name: str, week_key: str) -> Optional[models.LottoPurchase]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_PURCHASE), {"p1": user_id, "p2": user_name, "p3": week_key})).first()
        if row is None:
            return None
        return models.LottoPurchase(
            id=row[0],
            user_id=row[1],
            user_name=row[2],
            week_key=row[3],
            purchased_at=row[4],
        )

    async def find_purchase_by_user_and_week(self, *, user_id: str, week_key: str) -> Optional[models.LottoPurchase]:
        row = (await self._conn.execute(sqlalchemy.text(FIND_PURCHASE_BY_USER_AND_WEEK), {"p1": user_id, "p2": week_key})).first()
        if row is None:
            return None
        return models.LottoPurchase(
            id=row[0],
            user_id=row[1],
            user_name=row[2],
            week_key=row[3],
            purchased_at=row[4],
        )

    async def find_purchase_by_week_key(self, *, week_key: str) -> Optional[models.LottoPurchase]:
        row = (await self._conn.execute(sqlalchemy.text(FIND_PURCHASE_BY_WEEK_KEY), {"p1": week_key})).first()
        if row is None:
            return None
        return models.LottoPurchase(
            id=row[0],
            user_id=row[1],
            user_name=row[2],
            week_key=row[3],
            purchased_at=row[4],
        )
