# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class AlarmSetting:
    guild_id: str
    alarm_type: str
    channel_id: str
    created_at: Optional[datetime.datetime]
    updated_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class LottoPurchase:
    id: int
    user_id: str
    user_name: str
    week_key: str
    purchased_at: Optional[datetime.datetime]
